#!/bin/bash
# GeoDocs - Quick Start Commands

echo "🚀 GeoDocs Startup Commands"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 You need 3 terminals:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 1 - API Server:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd \"/Users/mrstark/Desktop/Code PlayGround/GeoDocs\""
echo "npm run api"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 2 - Ngrok Tunnel:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "ngrok http 3000"
echo ""
echo "After ngrok starts, copy the HTTPS URL (e.g., https://xxxx.ngrok-free.app)"
echo "Then update app.json with:"
echo "  \"apiUrl\": \"https://xxxx.ngrok-free.app\""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "TERMINAL 3 - Expo:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd \"/Users/mrstark/Desktop/Code PlayGround/GeoDocs\""
echo "npm start"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📱 After all 3 are running:"
echo "  1. Scan QR code with Expo Go"
echo "  2. Test PDF search in app"
echo ""

